01 = { path = "dfw-love-hurts-poster.webp", caption = "Official poster featuring [Chris Hunter](@/w/chris-hunter.md), [PJ Blake](@/w/pj-blake.md), [Revage](@/w/rafael-kid.md) and [Corin Maer](@/w/corin-mear.md).", source = "Official DFW Facebook" }

02 = { path = ".webp", caption = "Image announcing .", source = "Official DFW Facebook" }
03 = { path = ".webp", caption = "Image announcing .", source = "Official DFW Facebook" }
04 = { path = ".webp", caption = "Image announcing .", source = "Official DFW Facebook" }
05 = { path = ".webp", caption = "Image announcing .", source = "Official DFW Facebook" }
06 = { path = ".webp", caption = "Image announcing .", source = "Official DFW Facebook" }
07 = { path = ".webp", caption = "Image announcing .", source = "Official DFW Facebook" }
08 = { path = ".webp", caption = "Image announcing .", source = "Official DFW Facebook" }
