1 = { path = "2017-11-18-kpw-arena-8-droga-bez-powrotu-plakat.jpg", caption = "Official poster. Shown are: [Peter Pannache](@/w/peter-pannache.md), [Robert Star](@/w/robert-star.md), [Piękny Kawaler](@/w/piekny-kawaler.md), [Greg](@/w/greg.md), [Kamil Aleksander](@/w/kamil-aleksander.md) and [Bianca](@/w/bianca.md).", source = "kpwrestling.pl / Official KPW Facebook" }
2 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
3 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
4 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
5 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
6 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
