1 = { path = "2023-08-18-kpw-godzina-zero-2023-plakat.jpg", caption = "Official poster, featuring Iestyn Rees with a clock.", source = "kpwrestling.pl / Official KPW Facebook" }
2 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
3 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
4 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
5 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
6 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
7 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }
8 = { path = ".webp", caption = "Image announcing .", source = "Official KPW Facebook" }