[01]
path = "2024-09-07-kpw-godzina-zero-2024-plakat.jpg"
caption = "Official poster. In the top row are [Michał Fux](@/w/michal-fux.md), [Filip Fux](@/w/filip-fux.md), [Chemik](@/w/chemik.md), Red Scorpion with the [KPW Championship](@/c/kpw-championship.md) belt, and The 87. Next to the event name are smaller figures of [David Oliwa](@/w/david-oliwa.md), [Rosetti](@/w/rosetti.md), [Flexos](@/w/flexos.md) and [Ron Corvus](@/w/ron-corvus.md). At the bottom, we see Carlos Zamora, Reece Alexios, [Greg](@/w/greg.md), Jack Jester, [Hans Schulte](@/w/hans-schulte.md), [Zefir](@/w/zefir.md), [Leon Lato](@/w/leon-lato.md), [Darius](@/w/darius.md) and [Eryk Lesak](@/w/eryk-lesak.md)."
source = "kpwrestling.pl / Official KPW Facebook"

[02]
path = "bracia-fux-vs-the-87.webp"
caption = "Image announcing [Michał Fux](@/w/michal-fux.md) & [Filip Fux](@/w/filip-fux.md) vs Alexander Roth & Roy Johnson."
source = "Official KPW Facebook"

[03]
path = "leon-lato-vs-reece-alexios.webp"
caption = "Image announcing [Leon Lato](@/w/leon-lato.md) vs Reece Alexios."
source = "Official KPW Facebook"

[04]
path = "greg-vs-ron-corvus.webp"
caption = "Image announcing [Greg](@/w/greg.md) vs [Ron Corvus](@/w/ron-corvus.md)."
source = "Official KPW Facebook"

[05]
path = "chemik-vs-carlos-zamora.webp"
caption = "Image announcing [Chemik](@/w/chemik.md) vs Carlos Zamora."
source = "Official KPW Facebook"

[06]
path = "siedmiu-wspanialych.webp"
caption = "Image announcing [Zefir](@/w/zefir.md) vs [Darius](@/w/darius.md) vs [David Oliwa](@/w/david-oliwa.md) vs [Eryk Lesak](@/w/eryk-lesak.md) vs [Flexos](@/w/flexos.md) vs [Hans Schulte](@/w/hans-schulte.md) vs [Rosetti](@/w/rosetti.md)."
source = "Official KPW Facebook"

[07]
path = "red-scorpion-vs-jack-jester.webp"
caption = "Image announcing [Red Scorpion](@/w/red-scorpion.md) vs Jack Jester."
source = "Official KPW Facebook"

[10]
path = "2024-09-07-kpw-godzina-zero-2024-zefir-microphone.jpg"
caption = "Left to right: [Eryk Lesak](@/w/eryk-lesak.md), [Darius](@/w/darius.md), [Flexos](@/w/flexos.md), [Rosetti](@/w/rosetti.md), [Hans Schulte](@/w/hans-schulte.md) and [Zefir](@/w/zefir.md) with a microphone."
source = "M3n747"

[11]
path = "2024-09-07-kpw-godzina-zero-2024-zefir-unmasked.jpg"
caption = "Zefir unmasked."
source = "M3n747"

[12]
path = "torpeda-malinowska.webp"
caption = "Krystian Malinowski holds up a bottle of raspberry-flavoured [Soplica](https://en.wikipedia.org/wiki/Soplica) vodka with a custom label, which he was gifted by a fan after the show."
source = "PrezesMalinowskiKPW @ Facebook"
