0000 = { path = "kpw-arena-34-fantastyczny-plakat.webp", caption = "Official poster, featuring [Tomczak](@/w/tomczak.md) (back), [Leon Lato](@/w/leon-lato.md) (left), [Chemik](@/w/chemik.md) (right) and [Zefir](@/w/zefir.md) (front).", source = "kpwrestling.pl / Official KPW Facebook" }
0001 = { path = "tournee-lesaka.webp", caption = "Image announcing [Eryk Lesak's](@/w/eryk-lesak.md) upcoming appearances.", source = "ErykLesak @ Facebook" }
0002 = { path = "lesak-vs-paskal.webp", caption = "Image announcing [Eryk Lesak](@/w/eryk-lesak.md) vs [Markus Paskal](@/w/markus-paskal.md).", source = "Official KPW Facebook" }
0003 = { path = "four-way-match.webp", caption = "Image announcing [Leon Lato](@/w/leon-lato.md) vs [Zefir](@/w/zefir.md) vs [Chemik](@/w/chemik.md) vs [Tomczak](@/w/tomczak.md).", source = "Official KPW Facebook" }
0004 = { path = "oskar-haller-bedzie.webp", caption = "Image announcing [Oskar Haller](@/w/oskar-haller.md).", source = "Official KPW Facebook" }
0005 = { path = "kurde-to-co-oni-na-godzine-zero-w-takim-razie-szykuja.webp", caption = "Image announcing [Olgierd](@/w/olgierd.md) vs [Filip Fux](@/w/filip-fux.md).", source = "Official KPW Facebook" }
0006 = { path = "ricky-sky-vs-kamil-aleksander.webp", caption = "Image announcing [Ricky Sky](@/w/ricky-sky.md) vs [Kamil Aleksander](@/w/kamil-aleksander.md).", source = "Official KPW Facebook" }
0007 = { path = "michal-fux-vs-greg.webp", caption = "Image announcing [Michał Fux](@/w/michal-fux.md) vs [Greg](@/w/greg.md).", source = "Official KPW Facebook" }
0008 = { path = "fuksy-sie-ze-soba-rozmowia.webp", caption = "Image announcing [Michał Fux](@/w/michal-fux.md) and [Filip Fux](@/w/filip-fux.md).", source = "Official KPW Facebook" }

0010 = { path = "nowe-kable-stary-ring.webp", caption = "The ring before the show.", source = "M3n747" }
0011 = { path = "zefir-ultras.webp", caption = "Zefir ultras.", source = "M3n747" }
0012 = { path = "kinga-of-the-ringa.webp", caption = "[Kinga Miotke](@/w/kinga-miotke.md) opens the show.", source = "M3n747" }

0101 = { path = "z-innego-kata-patrzac-wcale-nie-jest-mniej-lysy.webp", caption = "[Olgierd's](@/w/olgierd.md) entrance.", source = "Alex Bałdyga" }
0102 = { path = "no-i-kaucja-poszla-sie---.webp", caption = "A crushed can of Olgierd's energy drink (resulting in a waste of a 0.5&nbsp;PLN deposit).", source = "M3n747" }
0103 = { path = "to-nie-slonce-to-lysina.webp", caption = "Olgierd approaches Filip Fux with a Flying Headbutt.", source = "M3n747" }
0104 = { path = "co-cztery-glowy-to-nie-dwie.webp", caption = "[Olgierd](@/w/olgierd.md) knows Filip Fux (biblically).", source = "M3n747" }
0105 = { path = "lysy-nelson.webp", caption = "[Olgierd](@/w/olgierd.md) suffers in Filip Fux's Full Nelson Hold.", source = "M3n747" }
0106 = { path = "sedzia-wiadomo-co.webp", caption = "Filip Fux cheats to win.", source = "M3n747" }
0107 = { path = "nie-liczy-sie-oszukiwal.webp", caption = "[Filip Fux](@/w/filip-fux.md) wins, but at what cost?", source = "M3n747" }











0201 = { path = ".webp", caption = ".", source = "M3n747" }
0301 = { path = ".webp", caption = ".", source = "M3n747" }
0401 = { path = ".webp", caption = ".", source = "M3n747" }
0501 = { path = ".webp", caption = ".", source = "M3n747" }
0601 = { path = ".webp", caption = ".", source = "M3n747" }
0701 = { path = ".webp", caption = ".", source = "M3n747" }
0801 = { path = ".webp", caption = ".", source = "M3n747" }
0901 = { path = ".webp", caption = ".", source = "M3n747" }


1001 = { path = "zefir-i-podmuszek.webp", caption = "[Zefir](@/w/zefir.md) with a custom Zefir action figure hand-made by a fan.", source = "M3n747" }
1002 = { path = "kppw.webp", caption = "[Krystian Malinowski](@/w/krystian-malinowski.md) and [Olgierd](@/w/olgierd.md) shake hands, symbolically ushering in a new era for KPW.", source = "M3n747" }
