0000 = { path = "kpw-arena-34-fantastyczny-plakat.webp", caption = "Official poster, featuring [Tomczak](@/w/tomczak.md) (back), [Leon Lato](@/w/leon-lato.md) (left), [Chemik](@/w/chemik.md) (right) and [Zefir](@/w/zefir.md) (front).", source = "kpwrestling.pl / Official KPW Facebook" }
0001 = { path = "tournee-lesaka.webp", caption = "Image announcing [Eryk Lesak's](@/w/eryk-lesak.md) upcoming appearances.", source = "ErykLesak @ Facebook" }
0002 = { path = "lesak-vs-paskal.webp", caption = "Image announcing [Eryk Lesak](@/w/eryk-lesak.md) vs [Markus Paskal](@/w/markus-paskal.md).", source = "Official KPW Facebook" }
0003 = { path = "four-way-match.webp", caption = "Image announcing [Leon Lato](@/w/leon-lato.md) vs [Zefir](@/w/zefir.md) vs [Chemik](@/w/chemik.md) vs [Tomczak](@/w/tomczak.md).", source = "Official KPW Facebook" }
0004 = { path = "oskar-haller-bedzie.webp", caption = "Image announcing [Oskar Haller](@/w/oskar-haller.md).", source = "Official KPW Facebook" }
0005 = { path = "kurde-to-co-oni-na-godzine-zero-w-takim-razie-szykuja.webp", caption = "Image announcing [Olgierd](@/w/olgierd.md) vs [Filip Fux](@/w/filip-fux.md).", source = "Official KPW Facebook" }
0006 = { path = "ricky-sky-vs-kamil-aleksander.webp", caption = "Image announcing [Ricky Sky](@/w/ricky-sky.md) vs [Kamil Aleksander](@/w/kamil-aleksander.md).", source = "Official KPW Facebook" }
0007 = { path = "michal-fux-vs-greg.webp", caption = "Image announcing [Michał Fux](@/w/michal-fux.md) vs [Greg](@/w/greg.md).", source = "Official KPW Facebook" }
0008 = { path = "fuksy-sie-ze-soba-rozmowia.webp", caption = "Image announcing [Michał Fux](@/w/michal-fux.md) and [Filip Fux](@/w/filip-fux.md).", source = "Official KPW Facebook" }

0010 = { path = "nowe-kable-stary-ring.webp", caption = "The ring before the show.", source = "M3n747" }
0011 = { path = "zefir-ultras.webp", caption = "Zefir ultras.", source = "M3n747" }
0012 = { path = "kinga-of-the-ringa.webp", caption = "[Kinga Miotke](@/w/kinga-miotke.md) opens the show.", source = "M3n747" }

0101 = { path = "z-innego-kata-patrzac-wcale-nie-jest-mniej-lysy.webp", caption = "[Olgierd's](@/w/olgierd.md) entrance.", source = "Alex Bałdyga" }
0102 = { path = "no-i-kaucja-poszla-sie---.webp", caption = "A crushed can of Olgierd's energy drink (resulting in the waste of a 0.5&nbsp;PLN deposit).", source = "M3n747" }
0103 = { path = "to-nie-slonce-to-lysina.webp", caption = "Olgierd approaches Filip Fux with a Flying Headbutt.", source = "M3n747" }
0104 = { path = "co-cztery-glowy-to-nie-dwie.webp", caption = "[Olgierd](@/w/olgierd.md) knows Filip Fux (biblically).", source = "M3n747" }
0105 = { path = "lysy-nelson.webp", caption = "[Olgierd](@/w/olgierd.md) suffers in Filip Fux's Full Nelson Hold.", source = "M3n747" }
0106 = { path = "sedzia-wiadomo-co.webp", caption = "Filip Fux cheats to win.", source = "M3n747" }
0107 = { path = "nie-liczy-sie-oszukiwal.webp", caption = "[Filip Fux](@/w/filip-fux.md) wins, but at what cost?", source = "M3n747" }

0201 = { path = "rookie-mistake.webp", caption = "Rookies [Three](@/w/rookie-three.md), Two and Four are feeling overconfident.", source = "M3n747" }

0301 = { path = "i-want-you-to-know-im-gonna-be-fair.webp", caption = "[Sędzia Alan](@/w/sedzia-alan.md) appreciates that Rookie Three shakes [Oskar Haller's](@/w/oskar-haller.md) hand.", source = "M3n747" }
0302 = { path = "scorpion-deathlock-z-drugiego-konca.webp", caption = "Oskar Haller shows [Rookie Two](@/w/rookie-two.md) what he's learned since joining the roster.", source = "M3n747" }
0303 = { path = "troche-niefortunnie-mi-ujecie-wyszlo-no-ale.webp", caption = "The legal [Rookie Two](@/w/rookie-two.md) throws the tagged out Rookie Three onto Oskar Haller.", source = "M3n747" }
0304 = { path = "konfuzjusz-mowi-cos-ci-sie-typie-pochrzanilo.webp", caption = "The tagged out Rookie Three launches himself at Oskar Haller, while the legal Rookie Two stands on the apron.", source = "M3n747" }
0305 = { path = "spoko-nastepnym-razem-sie-uda.webp", caption = "[Oskar Haller](@/w/oskar-haller.md) wins, while Rookies Two and Three argue.", source = "M3n747" }

0401 = { path = "kamil-powazny.webp", caption = "[Kamil Aleksander](@/w/kamil-aleksander.md).", source = "M3n747" }
0402 = { path = "rookie-four.webp", caption = "Rookie Four.", source = "M3n747" }
0403 = { path = "i-siup.webp", caption = "Kamil Aleksander hits a Suplex on Rookie Four.", source = "M3n747" }
0404 = { path = "patrzcie-to-jest-kamil.webp", caption = "[Sędzia Alan](@/w/sedzia-alan.md) declares [Kamil Aleksander](@/w/kamil-aleksander.md) the winner.", source = "M3n747" }
0405 = { path = "mlody-jest-spoko.webp", caption = "Kamil Aleksander shows respect to the young opponent.", source = "M3n747" }

0501 = { path = "ultimatum-gregorianskie.webp", caption = "[Greg](@/w/greg.md) delivers his ultimatum…", source = "M3n747" }
0502 = { path = "pop-lezy-krzyzem.webp", caption = "…and acts upon it.", source = "M3n747" }
0503 = { path = "zamienil-stryjek-drabine-na-kijek.webp", caption = "Greg sneakily grabs a conveniently-placed kendo stick from under the ring.", source = "M3n747" }
0504 = { path = "uzywane-czesci-samochodowe-u-fuksa.webp", caption = "Michał Fux about to hit [Greg](@/w/greg.md) with a used car hubcap. [Sędzia Alan](@/w/sedzia-alan.md) knows a good deal when he sees one.", source = "M3n747" }
0505 = { path = "pijus-pijusuje.webp", caption = "Greg renders unto himself that which is his.", source = "M3n747" }
0506 = { path = "klucz-do-sukcesu.webp", caption = "[Greg](@/w/greg.md) with a couple of adjustable spanners.", source = "M3n747" }
0507 = { path = "tool-assisted-nipple-twist.webp", caption = "Michał Fux turns [Greg's](@/w/greg.md) weapons on him.", source = "M3n747" }
0508 = { path = "boot-sequence.webp", caption = "[Michał Fux](@/w/michal-fux.md) lets a fan's shoe go to Greg's head.", source = "M3n747" }
0509 = { path = "a-bedzie-moze-rozmiar-46.webp", caption = "[Michał Fux](@/w/michal-fux.md) returns the shoe to its rightful owner.", source = "M3n747" }
0510 = { path = "dobrze-ze-ma-krotkie-wlosy.webp", caption = "Michał Fux enlightens Greg with a couple of lighttubes.", source = "M3n747" }
0511 = { path = "pinezki-sa-tylko-jeszcze-brakuje-takich-czerwonych-nitek.webp", caption = "Greg regains composure against the ropes, while [Michał Fux](@/w/michal-fux.md) is ready to spill a bag of push-pins onto the ring.", source = "M3n747" }
0512 = { path = "grzegorz-pierwszy-bolesciwy.webp", caption = "[Michał Fux](@/w/michal-fux.md) about to drop Greg onto the pins.", source = "M3n747" }
0513 = { path = "i-kto-to-teraz-bedzie-zamiatal.webp", caption = "[Sędzia Alan](@/w/sedzia-alan.md) awards the win to [Greg](@/w/greg.md).", source = "M3n747" }

0601 = { path = "tam-chyba-jest-cos-ciekawego.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md).", source = "M3n747" }
0602 = { path = "a-tam-u-gory-sa-az-dwie-rzeczy.webp", caption = "[Markus Paskal](@/w/markus-paskal.md).", source = "M3n747" }
0603 = { path = "dwaj-sympatyczni-mlodziency.webp", caption = "[Markus Paskal](@/w/markus-paskal.md) and [Eryk Lesak](@/w/eryk-lesak.md) before the match.", source = "M3n747" }
0604 = { path = "na-nastepnej-gali-mama-paskala-wygrywa-tytul-old-town.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md) argues with Paskal's Mum.", source = "M3n747" }
0605 = { path = "lesak-wstawaj-nie-udawaj.webp", caption = "The right Lesak in the right place.", source = "M3n747" }
0606 = { path = "wiedzialem-ze-w-koncu-da-rade.webp", caption = "Victorious Markus Paskal hugs it out with his loved ones.", source = "M3n747" }

0701 = { path = "krzysztof-krawczyk-na-miare-naszych-mozliwosci.webp", caption = "[Chemik](@/w/chemik.md) sows discord between Michał and Filip Fux.", source = "M3n747" }
0702 = { path = "doktur-potwur-w-plonacym-gumowym-szlafroku.webp", caption = "_Doctor_ Krystian Malinowski offers his diagnosis.", source = "M3n747" }
0703 = { path = "prosze-pana-ja-tu-od-wpol-do-siodmej-do-pana-doktora-czekam.webp", caption = "Filip Fux cannot face his brother, whom Chemik and [_doctor_ Krystian Malinowski](@/w/krystian-malinowski.md) play mind games with.", source = "M3n747" }
0704 = { path = "atlas-zbuntowany.webp", caption = "Michał Fux takes matters (and Krystian Malinowski) into his own hands.", source = "M3n747" }
0705 = { path = "jak-robie-tak-to-mnie-nie-widac.webp", caption = "Michał and [Filip Fux](@/w/filip-fux.md) reach a fork in the road of their lives.", source = "M3n747" }
0706 = { path = "brother-cutter.webp", caption = "Filip Fux makes a terrible decision.", source = "M3n747" }
0707 = { path = "brothers-no-more.webp", caption = "And thus ends the tale of the Brothers Fux.", source = "M3n747" }
0708 = { path = "sad-michal-in-the-ring.webp", caption = "[Michał Fux](@/w/michal-fux.md) alone and betrayed.", source = "M3n747" }

0801 = { path = "dzien-dobry-sprzedaje-te-fajne-bawelniane-szaliki.webp", caption = "[Chemik's](@/w/chemik.md) entrance. To the left stands [Kinga Miotke](@/w/kinga-miotke.md).", source = "M3n747" }
0802 = { path = "we-should-walk-summer.webp", caption = "A couple of Leon Lato's fans with a sign supporting their favourite wrestler.", source = "M3n747" }
0803 = { path = "no-bez-przesady-ta-lina-nie-jest-az-taka-twarda.webp", caption = "Chemik chokes Zefir against a rope. [Sędzia Alan](@/w/sedzia-alan.md) doesn't seem convinced.", source = "M3n747" }

0804 = { path = ".webp", caption = ".", source = "M3n747" }

0805 = { path = ".webp", caption = ".", source = "M3n747" }
0806 = { path = ".webp", caption = ".", source = "M3n747" }
0807 = { path = ".webp", caption = ".", source = "M3n747" }
0808 = { path = ".webp", caption = ".", source = "M3n747" }
0809 = { path = ".webp", caption = ".", source = "M3n747" }
0810 = { path = ".webp", caption = ".", source = "M3n747" }
0811 = { path = ".webp", caption = ".", source = "M3n747" }
0812 = { path = ".webp", caption = ".", source = "M3n747" }
0813 = { path = ".webp", caption = ".", source = "M3n747" }
0814 = { path = ".webp", caption = ".", source = "M3n747" }
0815 = { path = ".webp", caption = ".", source = "M3n747" }
0816 = { path = ".webp", caption = ".", source = "M3n747" }
0817 = { path = ".webp", caption = ".", source = "M3n747" }













0901 = { path = ".webp", caption = ".", source = "M3n747" }


1001 = { path = "zefir-i-podmuszek.webp", caption = "[Zefir](@/w/zefir.md) with a custom Zefir action figure hand-made by a fan.", source = "M3n747" }
1002 = { path = "kppw.webp", caption = "[Krystian Malinowski](@/w/krystian-malinowski.md) and [Olgierd](@/w/olgierd.md) shake hands, symbolically ushering in a new era.", source = "M3n747" }
