0000 = { path = "kpw-arena-32-plakat.webp", caption = "Official poster, featuring [Chemik](@/w/chemik.md), [Krystian Malinowski](@/w/krystian-malinowski.md) and [Filip Fux](@/w/filip-fux.md).", source = "kpwrestling.pl / Official KPW Facebook" }
0001 = { path = "kolejna-gala-kolejny-niemiec.webp", caption = "Image announcing [Filip Fux](@/w/filip-fux.md) vs Erik Asmus.", source = "Official KPW Facebook" }
0002 = { path = "a-to-schultaj.webp", caption = "Image announcing [Hans Schulte](@/w/hans-schulte.md).", source = "Official KPW Facebook" }
0003 = { path = "lesamik-vs-paskaleksander.webp", caption = "Image announcing [Eryk Lesak](@/w/eryk-lesak.md) & [Chemik](@/w/chemik.md) vs [Markus Paskal](@/w/markus-paskal.md) & [Kamil Aleksander](@/w/kamil-aleksander.md).", source = "Official KPW Facebook" }
0004 = { path = "gwidon.webp", caption = "Image announcing Guido Buriani.", source = "Official KPW Facebook" }
0005 = { path = "rozprawa.webp", caption = "Image announcing the court trial, featuring [Chemik](@/w/chemik.md), [Krystian Malinowski](@/w/krystian-malinowski.md) and [Filip Fux](@/w/filip-fux.md).", source = "Official KPW Facebook" }
0006 = { path = "michal-fux-vs-greg-vs-tomczak.webp", caption = "Image announcing [Michał Fux](@/w/michal-fux.md) vs [Greg](@/w/greg.md) vs [Tomczak](@/w/tomczak.md).", source = "Official KPW Facebook" }
0007 = { path = "leon-lato-vs-nico-narciso.webp", caption = "Image announcing [Leon Lato](@/w/leon-lato.md) vs Nico Narciso.", source = "Official KPW Facebook" }


1001 = { path = ".webp", caption = ".", source = "M3n747" }
1002 = { path = ".webp", caption = ".", source = "M3n747" }
1003 = { path = ".webp", caption = ".", source = "M3n747" }
1004 = { path = ".webp", caption = ".", source = "M3n747" }
1005 = { path = ".webp", caption = ".", source = "M3n747" }
1006 = { path = ".webp", caption = ".", source = "M3n747" }
1007 = { path = ".webp", caption = ".", source = "M3n747" }
1008 = { path = ".webp", caption = ".", source = "M3n747" }
1009 = { path = ".webp", caption = ".", source = "M3n747" }










2001 = { path = ".webp", caption = ".", source = "M3n747" }
3001 = { path = ".webp", caption = ".", source = "M3n747" }
4001 = { path = ".webp", caption = ".", source = "M3n747" }
5001 = { path = ".webp", caption = ".", source = "M3n747" }
6001 = { path = ".webp", caption = ".", source = "M3n747" }
7001 = { path = ".webp", caption = ".", source = "M3n747" }
8001 = { path = ".webp", caption = ".", source = "M3n747" }
