[01]
path = "2024-10-19-ptw-underground-23-plakat.jpg"
caption = """\
    Official poster. Pictured are: [Diana Strong](@/w/diana-strong.md), [Puncher](@/w/puncher.md), [Rust](@/w/rust.md), [Nano Lopez](@/w/nano-lopez.md), [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Arkadiusz Pawłowski](@/w/pan-pawlowski.md) and [Łukasz Okoński](@/w/lukasz-okonski.md)."""
source = "Official PTW Facebook"
[02]
path = "2024-10-19-ptw-underground-23-01_erik_slotir.jpg"
caption = """\
    [Erik Šlotíř](@/w/erik-slotir.md)"""
source = "Ville Paananen"
[03]
path = "2024-10-19-ptw-underground-23-02_miyagi_shida_with_a_ghostface_mask.jpg"
caption = """\
    [Miyagi Shida](@/w/miyagi-shida.md), wearing a [Ghostface](https://en.wikipedia.org/wiki/Ghostface_(Scream)) mask."""
source = "Ville Paananen"
[04]
path = "2024-10-19-ptw-underground-23-03_erik_slotir_slams_miyagi_shida.jpg"
caption = """\
    Erik Šlotíř slams Miyagi Shida; [Sędzia Klaudiusz](@/w/sedzia-klaudiusz.md) is in the background."""
source = "Ville Paananen"
[05]
path = "2024-10-19-ptw-underground-23-04_luca_bjorn_goes_through_the_table.jpg"
caption = """\
    Max Speed puts Luca Bjorn through the table."""
source = "Ville Paananen"
[06]
path = "2024-10-19-ptw-underground-23-05_max_speed_celebrating.jpg"
caption = """\
    [Max Speed](@/w/max-speed.md) wins!"""
source = "Ville Paananen"
[07]
path = "2024-10-19-ptw-underground-23-06_alex_brave_and_his_mystery_valet.jpg"
caption = """\
    [Alex Brave](@/w/alex-brave.md) and his mystery valet."""
source = "Ville Paananen"
[08]
path = "2024-10-19-ptw-underground-23-07_reyca.jpg"
caption = """\
    Reyca."""
source = "Ville Paananen"
[09]
path = "2024-10-19-ptw-underground-23-08_diana_strong.jpg"
caption = """\
    [Diana Strong](@/w/diana-strong.md)."""
source = "Ville Paananen"
[10]
path = "2024-10-19-ptw-underground-23-09_diana_strong_is_strong.jpg"
caption = """\
    [Diana Strong](@/w/diana-strong.md) bodyslams Reyca."""
source = "Ville Paananen"
[11]
path = "2024-10-19-ptw-underground-23-10_rust.jpg"
caption = """\
    [Rust](@/w/rust.md)."""
source = "Ville Paananen"
[12]
path = "2024-10-19-ptw-underground-23-11_serg_sullivan.jpg"
caption = """\
    Serg Sullivan."""
source = "Ville Paananen"
[13]
path = "2024-10-19-ptw-underground-23-12_mikk_vainula.jpg"
caption = """\
    Mikk Vainula."""
source = "Ville Paananen"
[14]
path = "2024-10-19-ptw-underground-23-13_mikk_vainula_slamming_serg_sullivan.jpg"
caption = """\
    Mikk Vainula slams Serg Sullivan; [Rust](@/w/rust.md) is on his knees; Sędzia Herno in the background."""
source = "Ville Paananen"
[15]
path = "2024-10-19-ptw-underground-23-14_mikk_vainula_throwing_rust.jpg"
caption = """\
    Mikk Vainula throws Rust."""
source = "Ville Paananen"
[16]
path = "2024-10-19-ptw-underground-23-15_tucker.jpg"
caption = """\
    Tucker on the second rope."""
source = "Ville Paananen"
[17]
path = "2024-10-19-ptw-underground-23-16_puncher.jpg"
caption = """\
    [Puncher](@/w/puncher.md) presents his belts; Tucker, [Arkadiusz Pawłowski](@/w/pan-pawlowski.md) and Sędzia Herno observe"""
source = "Ville Paananen"
[18]
path = "2024-10-19-ptw-underground-23-17_puncher_slamming_tucker.jpg"
caption = """\
    [Puncher](@/w/puncher.md) slams Tucker."""
source = "Ville Paananen"
[19]
path = "2024-10-19-ptw-underground-23-18_tucker_s_aerial_offence.jpg"
caption = """\
    Tucker drops onto Puncher."""
source = "Ville Paananen"