00002 = { path = "nadchodzace-gale.jpg", caption = "Image unveiling the name of the show, featuring [Jakub](@/w/jakub.md).", source = "Official Legacy Facebook" }
00003 = { path = "cut-legacy-wrestling.webp", caption = "The show's Ryucon-themed logo.", source = "Ryucon.pl" }
