00001 = { path = "low-5-plakat.webp", caption = "Official poster, featuring [Jakub](@/w/jakub.md).", source = "Official Legacy Facebook" }
00002 = { path = "chemik-vs-speed.webp", caption = "Image announcing [Chemik](@/w/chemik.md) vs [Max Speed](@/w/max-speed.md).", source = "Official Legacy Facebook" }
00003 = { path = "fox-vs-fux.webp", caption = "Image announcing [Jakub](@/w/jakub.md) vs [Filip Fux](@/w/filip-fux.md).", source = "Official Legacy Facebook" }
