0001 = { path = "legacy-6-ale-trent-7.webp", caption = "Official poster featuring Trent Seven, [Jakub](@/w/jakub.md) and [Max Speed](@/w/max-speed.md).", source = "Official Legacy Facebook" }
0002 = { path = "nadchodzace-gale.jpg", caption = "Image unveiling the name of the show, featuring [Jakub](@/w/jakub.md).", source = "Official Legacy Facebook" }
0003 = { path = "cut-legacy-wrestling.webp", caption = "The show's Ryucon-themed logo.", source = "Ryucon.pl" }
0004 = { path = "tournee-lesaka.webp", caption = "Image announcing [Eryk Lesak's](@/w/eryk-lesak.md) upcoming appearances.", source = "ErykLesak @ Facebook", skip_art = true }
0005 = { path = "dziedzister.webp", caption = "Image announcing [Syriusz Dziedzic](@/w/dziedzic.md) vs [Sinister](@/w/sinister.md).", source = "Official Legacy Facebook" }
0006 = { path = "speedman.webp", caption = "Image announcing [Wiktor Longman](@/w/wiktor-longman.md) vs [Max Speed](@/w/max-speed.md).", source = "Official Legacy Facebook" }
0007 = { path = "zefilgierd.webp", caption = "Image announcing [Zefir](@/w/zefir.md) vs [Olgierd](@/w/olgierd.md).", source = "Official Legacy Facebook" }
0008 = { path = "zabije-go-wygalaczka-zobaczycie.webp", caption = "Image announcing Trent Seven vs [Jakub](@/w/jakub.md).", source = "Official Legacy Facebook" }
009 = { path = "gauntlet1.webp", caption = "Image announcing [Sam Della Valle](@/w/sam-rogers.md).", source = "Official Legacy Facebook" }
0010 = { path = "obstawiam-ze-anonim-to-chemik.webp", caption = "Image announcing [Eryk Lesak](@/w/eryk-lesak.md) & ??? & [Tony Sheen](@/w/riverman.md) vs [Bartosz Plata](@/w/plata.md) & [Disco Pablo](@/w/disco-pablo.md) & [Marcelito](@/w/marcelito.md).", source = "Official Legacy Facebook" }

0101 = { path = "ring-przed.webp", caption = "The ring before the show.", source = "M3n747" }
0102 = { path = "wiktor-tanczy-krakowiaka.webp", caption = "Wiktor D. enters the arena.", source = "M3n747" }
0103 = { path = "wiktor-sie-stesknil.webp", caption = "Wiktor D. happy to see the ring.", source = "M3n747" }
0104 = { path = "zwyciezca-dlugi-czlowiek.webp", caption = "[Wiktor D.](@/w/wiktor-longman.md) opens the show.", source = "M3n747" }
0105 = { path = "dajcie-czlowiekowi-reke.webp", caption = "[Jakub](@/w/jakub.md) offers Trent Seven his hand.", source = "M3n747" }
0106 = { path = "a-zabierze-caly-palec.webp", caption = "Trent Seven suggests that a single digit ought to be enough.", source = "M3n747" }

0201 = { path = "zefir-na-niebiesko.webp", caption = "[Zefir](@/w/zefir.md).", source = "M3n747" }
0202 = { path = "jakub-kran.webp", caption = "[Jacob Crane](@/w/jacob-crane.md).", source = "M3n747" }
0203 = { path = "no-nie-dadza-czlowiekowi-chwycic-liny-no.webp", caption = "Jacob Crane pulls Zefir away from the ropes.", source = "M3n747" }
0204 = { path = "polsko-japonski-zaklad-chiropraktyki-stosowanej.webp", caption = "[Jacob Crane](@/w/jacob-crane.md) holds zefir in a Sharpshooter.", source = "M3n747" }
0205 = { path = "zefir-w-swoim-zywiole.webp", caption = "Zefir from the top rope.", source = "M3n747" }
0206 = { path = "no-dobra-z-kranem-przegrac-to-nie-wstyd.webp", caption = "Zefir taps out.", source = "M3n747" }
0207 = { path = "crane-wygral.webp", caption = "[Jacob Crane](@/w/jacob-crane.md) wins, as declared by [Sędzia Seweryn](@/w/sedzia-seweryn.md).", source = "M3n747" }

0301 = { path = "dawid-syrczewski.webp", caption = "[Sinister](@/w/sinister.md).", source = "M3n747" }
0302 = { path = "dziedzic-pruski.webp", caption = "[Syriusz Dziedzic](@/w/dziedzic.md) interacts with the crowd on his way to the ring.", source = "M3n747" }
0303 = { path = "cos-ty-sie-w-siec-od-rivermana-ubral-czy-co.webp", caption = "Dziedzic at the feet of his [former master](@/w/sinister.md).", source = "M3n747" }
0304 = { path = "utasmowanie-syriusza.webp", caption = "[Syriusz Dziedzic](@/w/dziedzic.md) taped to the top rope.", source = "M3n747" }
0305 = { path = "ej-to-wbrew-przepisom-bhp.webp", caption = "[Sinister](@/w/sinister.md) smears Dziedzic's blood on his own face.", source = "M3n747" }
0306 = { path = "ten-stol-jawi-sie-rachitycznym.webp", caption = "A bloodied [Dziedzic](@/w/dziedzic.md) looks as [Sinister](@/w/sinister.md) narrowly escapes dropping onto a table.", source = "M3n747" }
0307 = { path = "chwycil-kozak-tatarzyna.webp", caption = "Sinister and Dziedzic pull each other by the hair…", source = "M3n747" }
0308 = { path = "zaden-z-nich-sie-nie-utrzymal.webp", caption = "…and they both hit the table.", source = "M3n747" }
0309 = { path = "panel-yaoi-to-nie-w-tej-sali.webp", caption = "Sinister about to attempt a pin on Syriusz Dziedzic..", source = "M3n747" }
0310 = { path = "ten-pan-wygral-gratulujemy.webp", caption = "Syriusz Dziedzic wins the match and thus his freedom.", source = "M3n747" }

0401 = { path = "marceli-przybyl-przypierdzielic.webp", caption = "[Marcelito's](@/w/marcelito.md) entrance.", source = "M3n747" }
0402 = { path = "wyraznie-targaja-nim-sprzeczne-emocje.webp", caption = "[Bartosz Plata](@/w/plata.md) poses for the crowd.", source = "M3n747" }
0403 = { path = "is-pablo-is-party.webp", caption = "[Disco Pablo](@/w/disco-pablo.md) comes in swinging.", source = "M3n747" }
0404 = { path = "lesaka-chyba-nie-stac-bo-jest-wyraznie-mniej-gruby.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md) with his [KPW OldTown Championship](@/c/kpw-old-town-championship.md).", source = "M3n747" }
0405 = { path = "mozliwe-przelotne-opady-i-lekkie-zalesaczenia.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md) spits water in the general direction of the fans.", source = "M3n747" }
0406 = { path = "jutro-napisza-o-tym-w-gazecie-w-lokalnym-dodatku-do-dodatku.webp", caption = "Biuro Prasowe: [Tony Sheen](@/w/riverman.md), [Arek Paterek](@/w/arek-paterek.md), [Eryk Lesak](@/w/eryk-lesak.md).", source = "M3n747" }
0407 = { path = "gangsterskie-znaki-bandy-niskiego-mintaja.webp", caption = "[Tony Sheen](@/w/riverman.md) points out the imbalance in the line-up of the two teams. Or perhaps talks about fish, who can tell.", source = "M3n747" }
0408 = { path = "bartosz-plata-pani-dobrodziejka-narzedzie-do-konserwacji-powierzchni-plaskich.webp", caption = "Bartosz Plata turns on his friends.", source = "M3n747" }
0409 = { path = "odsiecz-samborska.webp", caption = "[Sambor](@/w/sambor.md) to the rescue.", source = "M3n747" }
0410 = { path = "panowie-to-sie-nazywa-zeszyt-i-otwiera-sie-tak.webp", caption = "The members of Biuro Prasowe discuss strategy.", source = "M3n747" }
0411 = { path = "a-teraz-przeprowadzimy-ekstrakcje-osemek-przez-nozdrza.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md) torments Marcelito.", source = "M3n747" }
0412 = { path = "nie-zgasi-mu-swiatla-bo-ryby-z-oczywistych-przyczyn-nie-uzywaja-elektrycznosci.webp", caption = "Marcelito third-ropes Tony Sheen.", source = "M3n747" }
0413 = { path = "co-komu-po-biurze-skoro-i-tak-nikt-juz-prasy-nie-czyta.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md), [Arek Paterek](@/w/arek-paterek.md), [Bartosz Plata](@/w/plata.md) and [Tony Sheen](@/w/riverman.md) celebrate their victory.", source = "M3n747" }
0414 = { path = "w-tym-miejscu-padaja-praslowianskie-przeklenstwa.webp", caption = "Disco Pablo faced with the angry [Sambor](@/w/sambor.md).", source = "M3n747" }
0415 = { path = "jak-zaloze-to-mnie-nie-pozna-i-dalej-bedziemy-kumplami.webp", caption = "Sambor looks for spiritual guidance in his mask.", source = "M3n747" }
0416 = { path = "powinni-pogadac-przy-antalku-slowianskiego-miodu-to-by-sie-pogodzili.webp", caption = "Sambor pounds on Disco Pablo.", source = "M3n747" }
0417 = { path = "pucuj-mi-buty-to-moze-kiedys-zostaniesz-milionerem.webp", caption = "It is safe to say that [Sambor](@/w/sambor.md) and Disco Pablo are no longer on speaking terms.", source = "M3n747" }

0501 = { path = "ten-tamten-i-ten-drugi-a-wlasciwie-pierwszy.webp", caption = "Patrykos and [Oskar Haller](@/w/oskar-haller.md).", source = "M3n747" }
0502 = { path = "przy-takim-brzuchu-to-mu-pas-niepotrzebny.webp", caption = ".", source = "M3n747" }
0503 = { path = "takie-piwo-to-najwyzej-do-podlewania-piwonii.webp", caption = ".", source = "M3n747" }

0601 = { path = ".webp", caption = "[Sam Della Valle](@/w/sam-rogers.md) enters carrying a can of what just as well could be a deodorant, or a bear spray.", source = "M3n747" }
0602 = { path = ".webp", caption = "[Boro's](@/w/boro.md) entrance is as sexy as ever.", source = "M3n747" }
0603 = { path = ".webp", caption = "[Boro](@/w/boro.md) offers a rose to [Sam Della Valle](@/w/sam-rogers.md).", source = "M3n747" }
0604 = { path = ".webp", caption = "Boro appears to enjoy Filip Fux's improper dancing a tad too much.", source = "M3n747" }
0605 = { path = ".webp", caption = ".", source = "M3n747" }
0606 = { path = ".webp", caption = ".", source = "M3n747" }
0607 = { path = ".webp", caption = ".", source = "M3n747" }
0608 = { path = ".webp", caption = ".", source = "M3n747" }
0609 = { path = ".webp", caption = ".", source = "M3n747" }
0610 = { path = ".webp", caption = ".", source = "M3n747" }







0701 = { path = ".webp", caption = ".", source = "M3n747" }
0801 = { path = ".webp", caption = ".", source = "M3n747" }
0901 = { path = ".webp", caption = ".", source = "M3n747" }
1001 = { path = ".webp", caption = ".", source = "M3n747" }
