00001 = { path = "whats-on-the-poster.webp", caption = "Official poster.", source = "Official Legacy Facebook" }
00002 = { path = "szybko-za-lisem.webp", caption = "Image announcing [Jakub](@/w/jakub.md) vs [Max Speed](@/w/max-speed.md).", source = "Official Legacy Facebook" }
