01 = { path = "ppw-chcemy-krwi-plakat.jpg", caption = "Official poster.", source = "SplatFilmFest.com"}
02 = { path = "johnny-blade.webp", caption = "Image announcing the Halloween Street Fight, featuring [Johnny Blade](@/w/johnny-blade.md).", source = "Official PpW Facebook" }
03 = { path = "gustavs-biggest-nightmare-match.webp", caption = "Image announcing &quot;[Gustav's](@/w/gustav-gryffin.md) Biggest Nightmare Match&quot;.", source = "Official PpW Facebook" }
