0001 = { path = "turniej-typeshit.webp", caption = "Official poster, featuring [Goblin](@/w/goblin.md) (left), [Mister Z](@/w/mister-z.md) (right) and [Michael HT](@/w/michael-ht.md) (bottom-right).", source = "Official PpW Facebook"}
