001 = { path = "ppw-lecimy-dalej-plakat.webp", caption = "Official poster, featuring Gabriel Queen.", source = "Stage24.pl / Official PpW Facebook" }
002 = { path = "vicbriel-queendel.webp", caption = "Image announcing [Gabriel Queen](@/w/gabriel-queen.md) vs [Vic Golden](@/w/vic-golden.md).", source = "Official PpW Facebook" }
003 = { path = "ten-to-musi-wydawac-fortune-na-szczoteczki.webp", caption = "Image announcing [Bartosz Plata](@/w/plata.md) vs Danil Mamedov.", source = "Official PpW Facebook" }
004 = { path = "emil-voeller-vs-jacob-crane.webp", caption = "Image announcing Emil Völler vs [Jacob Crane](@/w/jacob-crane.md).", source = "Official PpW Facebook" }
005 = { path = "gustav-gryffin-goblin-vs-antoni-ocean-leon-lato.webp", caption = "Image announcing [Gustav Gryffin](@/w/gustav-gryffin.md) & [Goblin](@/w/goblin.md) vs [Antoni Ocean](@/w/antoni-ocean.md) & [Leon Lato](@/w/leon-lato.md).", source = "Official PpW Facebook" }
006 = { path = "czlowiek-w-opasce-vs-czlowiek-w-kaszkiecie.webp", caption = "Image announcing [Gabriel Queen](@/w/gabriel-queen.md) vs [Vic Golden](@/w/vic-golden.md).", source = "Official PpW Facebook" }
007 = { path = "lysy-vs-rudy.webp", caption = "Image announcing [Olgierd](@/w/olgierd.md) vs [Jakub](@/w/jakub.md). In the background is the special guest referee, [Mister Z](@/w/mister-z.md).", source = "Official PpW Facebook" }
008 = { path = "hardkory-vs-rodzina.webp", caption = "Image announcing [Johnny Blade](@/w/johnny-blade.md) & [Biesiad Strong](@/w/biesiad.md) vs [Isnorr](@/w/isnorr.md) & [Filip Fux](@/w/filip-fux.md). (Note the typo: _Wrcoławski_ instead of _Wrocławski_.)", source = "Official PpW Facebook" }
009 = { path = "borutant-vs-zeriturick.webp", caption = "Image announcing [Boro](@/w/boro.md) & [Mutant](@/w/mutant.md) vs [Zeritus](@/w/zeritus.md) & Maverick.", source = "Official PpW Facebook" }
010 = { path = "kibicujemy-dalej.webp", caption = "The ring before the show.", source = "Ville Paananen" }

101 = { path = "jakub-kranowski.webp", caption = "[Jacob Crane](@/w/jacob-crane.md).", source = "Ville Paananen" }
102 = { path = "emil-folerowicz.webp", caption = "Emil Völler.", source = "Ville Paananen" }

201 = { path = "micharolutantoro.webp", caption = "Left to right: Michael HT, [Sędzia Karol Górski](@/w/sedzia-karol-gorski.md), Mutant, [Boro](@/w/boro.md).", source = "Ville Paananen" }
202 = { path = "jego-mawerycznosc.webp", caption = "Maverick.", source = "Ville Paananen" }
203 = { path = "zaraz-mavericka-zmutuje.webp", caption = "[Zeritus](@/w/zeritus.md) observes as [Mutant](@/w/mutant.md) faces Maverick.", source = "Ville Paananen" }
204 = { path = "no-zeritus-sie-zaraz-wkurzy.webp", caption = "[Zeritus](@/w/zeritus.md) is offended by Mutant's offence.", source = "Ville Paananen" }
205 = { path = "a-jednak-mutant-wkurzyl-sie-bardziej.webp", caption = "[Zeritus](@/w/zeritus.md) about to get his face introduced to the turnbuckle by Mutant.", source = "Ville Paananen" }

301 = { path = "danil-mamedov.webp", caption = "Danil Mamedov's entrance.", source = "Ville Paananen" }
302 = { path = "bartosz-plata.webp", caption = "[Bartosz Plata's](@/w/plata.md) entrance. To the left stands [Sędzia Karol Górski](@/w/sedzia-karol-gorski.md)", source = "Ville Paananen" }
303 = { path = "plata-rzuca-danilem.webp", caption = "Bartosz Plata slams Danil Mamedov. To the right stands [Sędzia Karol Górski](@/w/sedzia-karol-gorski.md).", source = "Ville Paananen" }

401 = { path = "czrwn-gng.webp", caption = "[Olgierd's](@/w/olgierd.md) entrance.", source = "Ville Paananen" }
402 = { path = "olgierd-i-jakub.webp", caption = "Olgierd and [Jakub](@/w/jakub.md).", source = "Ville Paananen" }
403 = { path = "fight-krzeslo-with-krzeslo.webp", caption = "Olgierd vs [Jakub](@/w/jakub.md). To the right is the special guest referee, Mister Z.", source = "Ville Paananen" }

501 = { path = "bo-wszyscy-wrestlerzy-to-jedna-rodzina.webp", caption = "Isnorr and Filip Fux.", source = "Ville Paananen" }

601 = { path = "lato-nad-oceanem.webp", caption = "Leon Lato and Antoni Ocean.", source = "Ville Paananen" }
602 = { path = "bad-trip.webp", caption = "Gustav Gryffin and Goblin's entrance.", source = "Ville Paananen" }
603 = { path = "good-trip.webp", caption = "[Gustav Gryffin](@/w/gustav-gryffin.md) and Goblin win.", source = "Ville Paananen" }

701 = { path = "gabrys-z-pasem.webp", caption = "[Gabriel Queen](@/w/gabriel-queen.md) with his [PpW Championship](@/c/ppw-championship.md). In the background [Sędzia Seweryn](@/w/sedzia-seweryn.md) has a belt too. ", source = "Ville Paananen" }
702 = { path = "lech-viclesa.webp", caption = "[Vic Golden](@/w/vic-golden.md).", source = "Ville Paananen" }
703 = { path = "jeden-czlowiek-a-ile-pasow.webp.webp", caption = "[Sędzia Seweryn](@/w/sedzia-seweryn.md) presents the [PpW Championship](@/c/ppw-championship.md), as Gabriel Queen and [Vic Golden](@/w/vic-golden.md) prepare for the fight.", source = "Ville Paananen" }
704 = { path = "vic-golden-chyba-nie-jest-zadowolony-z-obrotu-sytuacji.webp", caption = "Gabriel Queen slams Vid Golden's body.", source = "Ville Paananen" }
705 = { path = "zawsze-jest-tyle-papierkowej-roboty.webp", caption = "Vic Golden responds by stapling a photo to Gabriel Queen's face.", source = "Ville Paananen" }

706 = { path = ".webp", caption = ".", source = "Ville Paananen" }

707 = { path = ".webp", caption = ".", source = "Ville Paananen" }
708 = { path = ".webp", caption = ".", source = "Ville Paananen" }
709 = { path = ".webp", caption = ".", source = "Ville Paananen" }
710 = { path = ".webp", caption = ".", source = "Ville Paananen" }
711 = { path = ".webp", caption = ".", source = "Ville Paananen" }
712 = { path = ".webp", caption = ".", source = "Ville Paananen" }

801 = { path = ".webp", caption = ".", source = "Szymon Iwulski" }


