001 = { path = "ppw-brutality-plakat.webp", caption = 'Official poster, featuring Mutant.', source = "Official PpW Instagram" }
002 = { path = "irie-san.webp", caption = 'Image announcing [Shigehiro Irie](@/w/shigehiro-irie.md).', source = "Official PpW Facebook" }
