000 = { path = "dwa-na-dwa-plakat.webp", caption = "Official poster, featuring [Axel Fox](@/w/jakub.md), [Olgierd](@/w/olgierd.md), [Marco Hammers](@/w/marco-hammers.md), [Vic Golden](@/w/vic-golden.md) and [Oskar Alexander](@/w/oskar-alexander.md).", source = "Official PpW Facebook" }
001 = { path = "dwa-na-dwa-zapowiedz.webp", caption = "Announcement image, featuring the [PpW Tag Team Championship](@/c/ppw-tag-team-championship.md).", source = "Official PpW Facebook" }
002 = { path = "krolowa-radosci.webp", caption = "Image announcing [Gabriel Queen](@/w/gabriel-queen.md) vs [Justin Joy](@/w/justin-joy.md).", source = "Official PpW Facebook" }
003 = { path = "rodzinowablinstav.webp", caption = "Image announcing [Oskar Alexander](@/w/oskar-alexander.md) & [Filip Fux](@/w/filip-fux.md) vs [Mister Z](@/w/mister-z.md) & [Axel Fox](@/w/jakub.md) vs [Goblin](@/w/goblin.md) & [Gustav Gryffin](@/w/gustav-gryffin.md).", source = "Official PpW Facebook" }
004 = { path = "meska-meskosc.webp", caption = "Image announcing [Marco Hammers](@/w/marco-hammers.md) vs [Ladykiller](@/w/boro.md).", source = "Official PpW Facebook" }
005 = { path = "platasarax.webp", caption = "Image announcing [Bartosz Plata](@/w/plata.md) vs [Max Speed](@/w/max-speed.md) vs [Asara](@/w/asara.md).", source = "Official PpW Facebook" }
006 = { path = "pelen-bladosci.webp", caption = "Image announcing Emil Völler vs [Johnny Blade](@/w/johnny-blade.md).", source = "Official PpW Facebook" }
007 = { path = "lato-nad-oceanem.webp", caption = "Image announcing [Leon Lato](@/w/leon-lato.md) & [Antoni Ocean](@/w/antoni-ocean.md) vs [Sambor](@/w/sambor.md) & [Marcelito](@/w/marcelito.md).", source = "Official PpW Facebook" }
008 = { path = "sheetant.webp", caption = "Image announcing [Tony Sheen](@/w/riverman.md) vs [Mutant](@/w/mutant.md).", source = "Official PpW Facebook" }

101 = { path = "wroclawskie-lato.webp", caption = "[Leon Lato](@/w/leon-lato.md) debuts in PpW.", source = "M3n747" }
102 = { path = "tomczalito.webp", caption = "The unexpected debut of Tomczak, teaming up with Marcelito.", source = "M3n747" }
103 = { path = "surferito.webp", caption = "Antoni Ocean surfs on [Marcelito](@/w/marcelito.md).", source = "M3n747" }
104 = { path = "latocean-zwyciestwa.webp", caption = "Antoni Ocean and [Leon Lato](@/w/leon-lato.md) declared winners of the match by [Sędzia Karol Górski](@/w/madman-charlie.md).", source = "M3n747" }
105 = { path = "to-sie-zle-skonczy.webp", caption = "Tomczak about to do Marcelito violence.", source = "M3n747" }

200 = { path = "michal-hatewski.webp", caption = "[Michael HT](@/w/michael-ht.md).", source = "M3n747" }
201 = { path = "hi-im-bartosz.webp", caption = "[Bartosz Plata](@/w/plata.md) greets the crowd. In the back stands [Sędzia Seweryn](@/w/sedzia-seweryn.md).", source = "M3n747" }
202 = { path = "asara-wyluzowany.webp", caption = "[Asara](@/w/asara.md), unfazed by Plata's imposing presence.", source = "M3n747" }
203 = { path = "maksymilian-rychly.webp", caption = "[Max Speed](@/w/max-speed.md) victorious.", source = "M3n747" }

300 = { path = "ht-i-kornel.webp", caption = "[Michael HT](@/w/michael-ht.md) i [Sędzia Kornel](@/w/sedzia-kornel.md).", source = "M3n747" }
301 = { path = "sheeverman.webp", caption = "[Tony Sheen](@/w/riverman.md).", source = "M3n747" }
302 = { path = "daniela-boze-zmutowalo", caption = "[Mutant](@/w/mutant.md).", source = "M3n747" }
303 = { path = "dzieci-i-nobliwe-starowinki-niech-zamkna-oczy.webp", caption = "Suggestive shot of [Tony Sheen](@/w/riverman.md) manhandling [Mutant](@/w/mutant.md) against the ropes. To the left, [Sędzia Kornel](@/w/sedzia-kornel.md) appears mildly shocked.", source = "M3n747" }
304 = { path = "mutant-utopil-rivermana.webp", caption = "[Mutant](@/w/mutant.md) wins.", source = "M3n747" }

401 = { path = "boro-rozowy-i-rozany.webp", caption = "[Ladykiller](@/w/boro.md) with a bouquet of roses.", source = "M3n747" }
402 = { path = "hell-hit-me-hell-hit-me-not.webp", caption = "[Ladykiller](@/w/boro.md) holds the roses, as Marco gets down from a turnbuckle.", source = "M3n747" }
403 = { path = "shouldve-seen-this-coming-at-this-point.webp", caption = "[Ladykiller](@/w/boro.md) introduces his gloved hand to Marco's nethers, causing the jury to reel in shared pain.", source = "M3n747" }
404 = { path = "borowi-az-ciuch-zmienil-kolor.webp", caption = "Marco Hammers triumphs over Ladykiller.", source = "M3n747" }
405 = { path = "certyfikat-meskosci.webp", caption = "[Marco Hammers](@/w/marco-hammers.md) shows off his diploma of manliness.", source = "M3n747" }
406 = { path = "dostala-od-ladykillera-i-zyje.webp", caption = "A lady fan with one of [Ladykiller's](@/w/boro.md) roses.", source = "M3n747" }

501 = { path = "gabrys.webp", caption = "[Gabriel Queen](@/w/gabriel-queen.md) ready to go.", source = "M3n747" }
502 = { path = "trzej-weseli-panowie-bez-podtekstow.webp", caption = "Gabriel Queen and [Justin Joy](@/w/justin-joy.md) shake hands, much to [Sędzia Seweryn's](@/w/sedzia-seweryn.md) delight.", source = "M3n747" }
503 = { path = "ze-trzy-metry-jak-nic.webp", caption = "Justin Joy jumps from the top rope onto Gabriel Queen.", source = "M3n747" }
504 = { path = "we-are-the-champions.webp", caption = "[Gabriel Queen](@/w/gabriel-queen.md) wins the match.", source = "M3n747" }

601 = { path = "emilian-folerowicz.webp", caption = "Emil Völler.", source = "M3n747" }
602 = { path = "tajemniczy-zamaskowany-wrestler", caption = "[Johnny Blade](@/w/johnny-blade.md).", source = "M3n747" }
603 = { path = "chomik-alfred-was-here.webp", caption = "A rubber chicken. Don't ask.", source = "M3n747" }
604 = { path = "a-chair-a-man-but-no-chairman.webp", caption = "A broken chair, a dented cookie sheet and an unbeatable Johnny Blade.", source = "M3n747" }
605 = { path = "zuberek.webp", caption = "Emil Völler helps himself to some Polish beer…", source = "M3n747" }
606 = { path = "i-po-zuberku.webp", caption = "…which is quickly snatched from him by [Johnny Blade](@/w/johnny-blade.md).", source = "M3n747" }
607 = { path = "ciekawe-kto-to-bedzie-potem-sprzatal.webp.webp", caption = "Beer-related carnage. Beernage, if you will.", source = "M3n747" }
608 = { path = "na-takim-to-nawet-johnny-by-nie-usiadl.webp.webp", caption = "Emil Völler hits [Johnny Blade](@/w/johnny-blade.md) with a steel chair wrapped in barbed wire.", source = "M3n747" }
609 = { path = "krzeslo-siedzi-na-johnnym.webp.webp", caption = "A better view of the barbed wire chair, as Emil Völler presses it into Johnny Blade's head.", source = "M3n747" }

701 = { path = "podpisz-ten-papier-ziomek.webp", caption = "Johnny Blade signs Olgierd's Championship contract.", source = "M3n747" }
702 = { path = "samopodpisujace-sie-dokumenty-xxi-wieku.webp", caption = "[Johnny Blade](@/w/johnny-blade.md) signs the contract with Olgierd's hand.", source = "M3n747" }

801 = { path = ".webp", caption = ".", source = "M3n747" }
802 = { path = ".webp", caption = ".", source = "M3n747" }
803 = { path = ".webp", caption = ".", source = "M3n747" }
804 = { path = ".webp", caption = ".", source = "M3n747" }
805 = { path = ".webp", caption = ".", source = "M3n747" }
806 = { path = ".webp", caption = ".", source = "M3n747" }










901 = { path = "zajete-teriery.webp", caption = "Outside view of the venue after the show.", source = "M3n747" }
