001 = { path = "dojo-showcase.webp", caption = "Image announcing the showcase.", source = "Official Ewenement Dojo Facebook" }
002 = { path = "antoni-ocean.webp", caption = "Image announcing [Antoni Ocean](@/w/antoni-ocean.md).", source = "Official Ewenement Dojo Facebook" }
003 = { path = "olgierd-vs-unknown.webp", caption = "Image announcing [Olgierd](@/w/olgierd.md) vs ???.", source = "Official Ewenement Dojo Facebook" }
