001 = { path = "ppw-chaos-na-rewirach.webp", caption = 'Official poster, featuring [Mutant](@/w/mutant.md).', source = "Official PpW Facebook" }
002 = { path = "kran-krolowej.webp", caption = 'Image announcing [Jacob Crane](@/w/jacob-crane.md) vs [Gabriel Queen](@/w/gabriel-queen.md).', source = "Official PpW Facebook" }
