001 = { path = "inicjatywa-plakat.webp", caption = 'Official poster, featuring Gabriel Queen and Mister Z.', source = "Official PpW Facebook" }
002 = { path = "mutant-vs-blade.webp", caption = 'Image announcing [Mutant](@/w/mutant.md) vs [Johnny Blade](@/w/johnny-blade.md).', source = "Official PpW Facebook" }
