001 = { path = "ppw-wixapol.webp", caption = 'Official poster.', source = "Official PpW Facebook" }
002 = { path = "los-societas-de-las-poetas-ultraviolentas.webp", caption = 'Image announcing [Stanisław Van Dobroniak](@/w/stanislaw-van-dobroniak.md) vs [Johnny Blade](@/w/johnny-blade.md).', source = "Official PpW Facebook" }
