001 = { path = "ppw-polska-gurom.webp", caption = "Official poster featuring, top: [Jacob Crane](@/w/jacob-crane.md), [Mister Z](@/w/mister-z.md), [Johnny Blade](@/w/johnny-blade.md); bottom: [Goblin](@/w/goblin.md), [Gustav Gryffin](@/w/gustav-gryffin.md), [Olgierd](@/w/olgierd.md).", source = "bjw.co.jp"}
002 = { path = "patricks-vs-olgierd-crane-vs-irie.webp", caption = "Image announcing Dale Patricks vs [Olgierd](@/w/olgierd.md) and [Jacob Crane](@/w/jacob-crane.md) vs Shigehiro Irie.", source = "bjw.co.jp"}
003 = { path = "gabriel-queen-vs-unknown.webp", caption = "Image announcing [Gabriel Queen](@/w/gabriel-queen.md) vs a mystery opponent.", source = "bjw.co.jp"}

100 = { path = "gorilla-door.webp", caption = "The unassuming Gorilla position.", source = "Official PpW YouTube"}
100 = { path = "kran-i-shige.webp", caption = "[Jacob Crane](@/w/jacob-crane.md) and Shigehiro Irie.", source = "Official PpW YouTube"}
100 = { path = "olgierd-drugimi-drzwiami.webp", caption = "[Olgierd](@/w/olgierd.md).", source = "Official PpW YouTube"}
100 = { path = "patryk-w-dali.webp", caption = "Dale Patricks.", source = "Official PpW YouTube"}
100 = { path = "kran-pudluje-ale-nie-w-tym-sensie.webp", caption = "Jacob Crane attacks Dale Patricks with his own plastic container.", source = "Official PpW YouTube"}
100 = { path = "hai-faivo.webp", caption = "Shigehiro Irie high-fives a young fan.", source = "Official PpW YouTube"}
100 = { path = "polska-flaga-w-japonii.webp", caption = "[Olgierd](@/w/olgierd.md) plants the Polish flag in Shigehiro Irie's head.", source = "Official PpW YouTube"}
100 = { path = "mikroplastik-na-makrolbie.webp", caption = "Dale Patricks shatters a plastic lid over Olgierd's head.", source = "Official PpW YouTube"}
100 = { path = "bylo-san.webp", caption = "Referee Martyna counts the pin as Dale Patricks has Jacob Crane on the mat.", source = "Official PpW YouTube"}

200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}

200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
200 = { path = ".webp", caption = ".", source = "Official PpW YouTube"}
