[01]
path = "supronstars-1.jpg"
caption = "A photo from one of the shows. [Andrzej Supron](@/w/andrzej-supron.md) stands on the left, in black clothes."
source = "Wikipedia"

[02]
path = "supronstars-2.jpg"
caption = "A show in the Soviet Union, 1990."
source = "phil-lions-research.blogspot.com"

[03]
path = "supronstars-3.jpg"
caption = "Left to right: [Andrzej Supron](@/w/andrzej-supron.md), Władysław Komar and Evgeny Artyukhin."
source = "phil-lions-research.blogspot.com"

[04]
path = "supronstars-in-dushanbe.jpg"
caption = "Newspaper advert: the three shows in Dushanbe, Tajikistan.<br/>Note the names Анджей Супрон (Andrzej Supron) and Владислав Комар (Władysław Komar), as well as the promise of эротик шоу-балет (self-explanatory)."
source = "phil-lions-research.blogspot.com"

[05]
path = "supronstars-in-tashkent.jpg"
caption = "Newspaper advert: the shows in Tashkent, Uzbekistan.<br/>_&quot;Pro-resling&quot; and pro erotic show_."
source = "phil-lions-research.blogspot.com"

[06]
path = "supronstars-in-tomsk.jpg"
caption = "Newspaper advert: the six shows in Tomsk, Russia.<br/>The erotic show advertised under the name &quot;Новое поколение&quot; (_New generation_)."
source = "phil-lions-research.blogspot.com"

[07]
path = "supronstars-in-vilnius.jpg"
caption = "One of the two shows in Vilnius, Lithuania."
source = "phil-lions-research.blogspot.com"

[08]
path = "supronstars-in-almaty.jpg"
caption = "One or two of the ten shows in Almaty, Kazakhstan."
source = "phil-lions-research.blogspot.com"

[09]
path = "moskwa-01.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[10]
path = "moskwa-02.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[11]
path = "moskwa-03.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[12]
path = "moskwa-04.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[13]
path = "moskwa-05.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[14]
path = "moskwa-06.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[15]
path = "moskwa-07.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[16]
path = "moskwa-08.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[17]
path = "moskwa-09.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia.<br/>Władysław Komar flexes his muscles."
source = "sport-express.ru"

[18]
path = "moskwa-10.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[19]
path = "moskwa-11.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[20]
path = "moskwa-12.jpg"
caption = "The show at Dynamo Sports Palace in Moscow, Russia."
source = "sport-express.ru"

[21]
path = "gazeta-nowa-nr-28-z-dnia-1991-02.08-10-str-7.webp"
caption = "Newspaper article, critical of foxy boxing at a SupronStars show."
source = "zbc.uz.zgora.pl"
