01 = { path = "frpw-siedlce-plakat.webp", caption = "Official poster featuring [Jacob Crane](@/w/jacob-crane.md) vs ??? and [Leon Lato](@/w/leon-lato.md) vs ???.", source = "Official FRPW Facebook" }
