0001 = { path = "mzw-zjedz-mu-leb-plakat.webp", caption = "Official poster.", source = "Official MZW Facebook" }
0002 = { path = "disco-pablo-vs-oskar-alekander.webp", caption = "Image announcing [Disco Pablo](@/w/disco-pablo.md) vs [Oskar Alexander](@/w/oskar-alexander.md).", source = "Official MZW Facebook" }
