0001 = { path = "mzw-zjedz-mu-leb-plakat.webp", caption = "Official poster.", source = "Official MZW Facebook" }
0002 = { path = "dyskoteka-aleksandryjska.webp", caption = "Image announcing [Disco Pablo](@/w/disco-pablo.md) vs [Oskar Alexander](@/w/oskar-alexander.md).", source = "Official MZW Facebook" }
0003 = { path = "legia-podzielona.webp", caption = "Image announcing [Marco Hammers](@/w/marco-hammers.md) vs [Shadow](@/w/shadow.md) (top) and [Marcelito](@/w/marcelito.md) vs [Olgierd](@/w/olgierd.md) (bottom).", source = "Official MZW Facebook" }
0004 = { path = "wilk-szybko-zje-gryfa.webp", caption = "Image announcing [Febus 'The Wolf'](@/w/apollo-anderson.md) vs [Gustav Gryffin](@/w/gustav-gryffin.md) vs [Max Speed](@/w/max-speed.md).", source = "Official MZW Facebook" }
0005 = { path = "dziebuckna.webp", caption = "Image announcing [Syriusz Dziedzic](@/w/dziedzic.md) vs [Matt Buckna](@/w/matt-buckna.md).", source = "Official MZW Facebook" }
0006 = { path = "chodz-polowimy-razem-kraby.webp", caption = "Image announcing [Tony Sheen](@/w/riverman.md).", source = "Official MZW Facebook" }

1000 = { path = "uprzejmie-prosze-panstwa-przyszykowac-sie-do-rumblania.webp", caption = "[Adrian Zgórski](@/w/adrian-zgorski.md) opens the show.", source = "M3n747" }
1001 = { path = "felix-szwajcar.webp", caption = "Felix Schweizer's entrance.", source = "M3n747" }
1002 = { path = "o-ten-pan-wygral.webp", caption = "Tony Sheen wins, as declared by Sędzia Michał.", source = "M3n747" }

2001 = { path = "lysosc-legionu.webp", caption = "[Marco Hammers](@/w/marco-hammers.md) enters accompanied by [Olgierd](@/w/olgierd.md).", source = "M3n747" }
2002 = { path = "bog-jest-szalikiem.webp", caption = "_God is bald_.", source = "M3n747" }
2003 = { path = "marco-lize-powietrze.webp", caption = "A photo of [Marco Hammers](@/w/marco-hammers.md) posing for a photo.", source = "M3n747" }
2004 = { path = "marco-trzyma-shadowa.webp", caption = "[Marco Hammers](@/w/marco-hammers.md) applies a chokehold to [Shadow](@/w/shadow.md).", source = "M3n747" }
2005 = { path = "marco-dusi-shadowa.webp", caption = "Marco Hammers chokes [Shadow](@/w/shadow.md).", source = "M3n747" }

3001 = { path = "max-speed-whoop-whoop.webp", caption = "[Max Speed](@/w/max-speed.md) stands on the ropes; in the ring are [Gustav Gryffin](@/w/gustav-gryffin.md), [Febus 'The Wolf'](@/w/apollo-anderson.md) and [Sędzia Seweryn](@/w/sedzia-seweryn.md).", source = "M3n747" }
3002 = { path = "gustava-antyspidowa.webp", caption = "Gustav Gryffin powerbombs Max Speed, who suplexes Febus. In the background stands [Sędzia Seweryn](@/w/sedzia-seweryn.md).", source = "M3n747" }
3003 = { path = "ale-nim-rzucilo.webp", caption = "[Sędzia Seweryn](@/w/sedzia-seweryn.md) does a 180 Two-Count Break as [Max Speed](@/w/max-speed.md) kicks out.", source = "M3n747" }


4001 = { path = "", caption = ".", source = "M3n747" }


5001 = { path = "", caption = ".", source = "M3n747" }
6001 = { path = "", caption = ".", source = "M3n747" }
