0000 = { path = "mzw-no-time-to-die-2-plakat.webp", caption = "Official poster featuring, top: [Marco Hammers](@/w/marco-hammers.md), [Matt Buckna](@/w/matt-buckna.md); middle: [Disco Pablo](@/w/disco-pablo.md); bottom: [Marcelito](@/w/marcelito.md), [Shadow](@/w/shadow.md).", source = "Official MZW Facebook" }
0001 = { path = "no-time-to-die-2-zwiastun.webp", caption = "Image announcing the show.", source = "Official MZW Facebook" }
0002 = { path = "shadowcelito-vs-legiolysito.webp", caption = "Image announcing [Shadow](@/w/shadow.md) & [Marcelito](@/w/marcelito.md) vs [Olgierd](@/w/olgierd.md) & [Marco Hammers](@/w/marco-hammers.md).", source = "Official MZW Facebook" }
0003 = { path = "nie-axel-fox-vs-dalej-max-speed.webp", caption = "Image announcing [Jakub](@/w/jakub.md) vs [Max Speed](@/w/max-speed.md).", source = "Official MZW Facebook" }
0004 = { path = "disco-z-pablem.webp", caption = "Image announcing [Disco Pablo](@/w/disco-pablo.md) vs [Mister Z](@/w/mister-z.md).", source = "Official MZW Facebook" }
0005 = { path = "niemiec-vs-facet-ktory-nie-jest-niemcem-ale-troche-sie-nazywa-jakby-byl.webp", caption = "Image announcing [Matt Buckna](@/w/matt-buckna.md) vs [Gustav Gryffin](@/w/gustav-gryffin.md).", source = "Official MZW Facebook" }
0006 = { path = "toborombor.webp", caption = "Image announcing [Tony Sheen](@/w/riverman.md) vs [Boro](@/w/boro.md) vs [Sambor](@/w/sambor.md).", source = "Official MZW Facebook" }
0007 = { path = "oskar-sie-otworzyl.webp", caption = "Image announcing [Oskar Alexander](@/w/oskar-alexander.md).", source = "Official MZW Facebook" }
0008 = { path = "matt-buckna-jest-cieniem-samego-siebie.webp", caption = "Image announcing a new, unknown opponent for [Gustav Gryffin](@/w/gustav-gryffin.md).", source = "Official MZW Facebook" }
0009 = { path = "ten-z-czerwonego-kapturka-vs-dziedzic-pruski.webp", caption = "Image announcing [Febus 'The Wolf'](@/w/apollo-anderson.md) vs [Syriusz Dziedzic](@/w/dziedzic.md).", source = "Official MZW Facebook" }

0101 = { path = "o-kurcze-to-anonimowy-ochroniarz.webp", caption = "The ring before the show, guarded diligently by an [anonymous security guy](@/w/plata.md).", source = "M3n747" }
0102 = { path = "czy-sie-stoi-czy-sie-siedzi-kibicowac-sie-nalezy.webp", caption = "The other end of the room.", source = "M3n747" }
0103 = { path = "nie-wstane-tak-bede-lezal.webp", caption = "Adrian Zgórski making a ring angel.", source = "M3n747" }
0104 = { path = "no-juz-dobrze-niech-bedzie-ze-wstane.webp", caption = "Adrian Zgórski gets up with style.", source = "M3n747" }
0105 = { path = "ask-and-you-shall-receive-sort-of.webp", caption = "[Adrian Zgórski](@/w/adrian-zgorski.md) gives the people what they wanted - or at least the next best thing.", source = "M3n747" }
0106 = { path = "aquaman-po-20-latach-komunizmu.webp", caption = "Arek Paterek presents: [Tony Sheen](@/w/riverman.md).", source = "M3n747" }

1001 = { path = "mister-z-teczka.webp", caption = "Mister Z with his contract briefcase.", source = "M3n747" }
1002 = { path = "sedzia-michal.webp", caption = "[Sędzia Michał](@/w/sedzia-michal.md).", source = "M3n747" }
1003 = { path = "ja-w-klubie-disco-moge-robic-wszystko.webp", caption = "[Disco Pablo](@/w/disco-pablo.md).", source = "M3n747" }

2001 = { path = "lysy-i-lysszy.webp", caption = "[Olgierd](@/w/olgierd.md) & [Marco Hammers](@/w/marco-hammers.md).", source = "M3n747" }
2002 = { path = "matriksa-sie-naogladal.webp", caption = "[Marcelito](@/w/marcelito.md), wearing a leather coat similar to Shadow's.", source = "M3n747" }
2003 = { path = "szedo.webp", caption = "[Shadow](@/w/shadow.md), with [Marco Hammers](@/w/marco-hammers.md) in the background.", source = "M3n747" }
2004 = { path = "po-lysinach-do-zwyciestwa.webp", caption = "Marco Hammers about to jump from Olgierd's back onto Marcelito. To the right stands Sędzia Seweryn.", source = "M3n747" }
2005 = { path = "dwa-supleksy-w-cenie-jednego.webp", caption = "Sędzia Seweryn observes Marco Hammers and Olgierd performing a double Suplex on Marcelito.", source = "Kawczun" }
2006 = { path = "marceli-flip.webp", caption = "Shadow monkey flips Marcelito onto Marco Hammers.", source = "Kawczun" }
2007 = { path = "moonsaultyzm-stosowany.webp", caption = "Shadow hits a Moonsault on Marco Hammers. In the background stands Marcelito, [Sędzia Seweryn](@/w/sedzia-seweryn.md) to the right.", source = "Kawczun" }
2008 = { path = "co-ja-nie-zrobie-potrzymaj-mi-marcelita.webp", caption = "Marco Hammers holds Marcelito in a Delayed Vertical Suplex.", source = "M3n747" }
2009 = { path = "marcelito-zawsze-ma-zielone.webp", caption = "A strip of Marcelito's LED lights.", source = "M3n747" }





3001 = { path = ".webp", caption = ".", source = "M3n747" }
4001 = { path = ".webp", caption = ".", source = "M3n747" }
5001 = { path = ".webp", caption = ".", source = "M3n747" }
6001 = { path = ".webp", caption = ".", source = "M3n747" }
7001 = { path = ".webp", caption = ".", source = "M3n747" }
8001 = { path = ".webp", caption = ".", source = "M3n747" }
9001 = { path = ".webp", caption = ".", source = "M3n747" }
