0000 = { path = "mzw-na-zawsze-jak-batman.webp", caption = "Image announcing the show, featuring [Marco Hammers](@/w/marco-hammers.md) holding Marcelito in a Vertical Suplex. In the background, Tony Sheen swims on the left, and [Disco Pablo](@/w/disco-pablo.md) floats on the right.", source = "Official MZW Facebook" }
0001 = { path = "mzw-forever-2-zapowiedz.webp", caption = "Image announcing the show, featuring [Marco Hammers](@/w/marco-hammers.md).", source = "Official MZW Facebook" }
0002 = { path = "olgierd-vs-marcelito.webp", caption = "Image announcing [Olgierd](@/w/olgierd.md) vs [Marcelito](@/w/marcelito.md).", source = "Official MZW Facebook" }
0003 = { path = "batel-rojal.webp", caption = "Image announcing the Battle Royal.", source = "Official MZW Facebook" }
0004 = { path = "mlotek-utonie-w-rzece.webp", caption = "Image announcing [Tony Sheen](@/w/riverman.md) vs [Marco Hammers](@/w/marco-hammers.md).", source = "Official MZW Facebook" }
0005 = { path = "jakub-open-challenge.webp", caption = "Image announcing [Jakub](@/w/jakub.md).", source = "Official MZW Facebook" }
0006 = { path = "3-way-match.webp", caption = "Image announcing [Disco Pablo](@/w/disco-pablo.md) vs [Mutant](@/w/mutant.md) vs [Bartosz Plata](@/w/plata.md).", source = "Official MZW Facebook" }
0007 = { path = "speedzic.webp", caption = "Image announcing [Max Speed](@/w/max-speed.md) vs [Syriusz Dziedzic](@/w/dziedzic.md).", source = "Official MZW Facebook" }

0101 = { path = "na-razie-pusto.webp", caption = "The ring before the show.", source = "M3n747" }
0102 = { path = "ostry-deszczyng.webp", caption = "Heavy rain before the start of the event.", source = "M3n747" }
0103 = { path = "w-sumie-moglby-kiedys-zaspiewac.webp", caption = "[Adi](@/w/adrian-zgorski.md) opens the show.", source = "M3n747" }

1001 = { path = "czlowiek-wykalaczka.webp", caption = "[Jakub's](@/w/jakub.md) entrance.", source = "M3n747" }
1002 = { path = "rudy-z-rozowym.webp", caption = "Jakub receives a rose from [Boro](@/w/boro.md).", source = "M3n747" }

2001 = { path = "konflikt-pokolen.webp", caption = "_Rookies_ Adrian, Maciej and Marek gang up on Sambor, while _rookie_ Stefan attacks Boro.", source = "M3n747" }
2002 = { path = "ladny-macie-ring-byloby-szkoda-gdybyscie-z-niego-wypadli.webp", caption = "Sambor and Boro eliminate one another.", source = "M3n747" }

3001 = { path = "normalnie-zaraz-nas-czeka-dyskusja-shadowa-z-zefirem.webp", caption = "[Shadow](@/w/shadow.md) tells Jakub that the Legacy Championship Match is still on.", source = "M3n747" }
3002 = { path = "jakubie-odejdz-prosze.webp", caption = "Sambor and Boro make sure that Jakub is out.", source = "M3n747" }

4001 = { path = "tyski-przyrzad-do-swiecenia-pod-zadkiem.webp", caption = "[Marcelito](@/w/marcelito.md) with a customised chair.", source = "M3n747" }
4002 = { path = "launchelito.webp", caption = "[Marcelito](@/w/marcelito.md) launches himself at Olgierd.", source = "M3n747" }
4003 = { path = "marcel-splash.webp", caption = "Marcelito about to hit Olgierd with a Frog Splash.", source = "M3n747" }
4004 = { path = "sluzy-do-siedzenia-nie-do-duszenia.webp", caption = ".", source = "M3n747" }
4005 = { path = "wingierd.webp", caption = "[Olgierd](@/w/olgierd.md) wins.", source = "M3n747" }

5001 = { path = "sambor-na-linie.webp", caption = "[Sambor's](@/w/sambor.md) entrance leaves [Sędzia Karol Górski](@/w/sedzia-karol-gorski.md) impressed.", source = "M3n747" }
5002 = { path = "jakubie-nie-bij.webp", caption = "[Jakub](@/w/jakub.md) attacks [Boro](@/w/boro.md) before the start of the match.", source = "M3n747" }
5003 = { path = "sambor-aaaaa.webp", caption = "[Sambor](@/w/sambor.md) is angry.", source = "M3n747" }
5004 = { path = "sambor-bbbbb.webp", caption = "[Sambor](@/w/sambor.md) is very angry.", source = "M3n747" }
5005 = { path = "ten-lysy-w-pierwszym-rzedzie-wyglada-jak-dobry-brat-blizniak-chemika.webp", caption = "Boro puts on a rubber glove…", source = "M3n747" }
5006 = { path = "plop.webp", caption = "…and introduces an opposable thumb to [Sambor's](@/w/sambor.md) alimentary.", source = "M3n747" }
5007 = { path = "jakubowi-sie-wygralo.webp", caption = "[Jakub](@/w/jakub.md) wins.", source = "M3n747" }

5101 = { path = "they-wrestle-we-watch.webp", caption = "Adi reduced to his pure essence.", source = "M3n747" }
5102 = { path = "adi-w-adidasach.webp", caption = "[Adrian Zgórski's](@/w/adrian-zgorski.md) spirit inhabiting a mortal body.", source = "M3n747" }

6001 = { path = "ej-no-juz-wystarczy-ze-na-zewnatrz-pada.webp", caption = "[Syriusz Dziedzic's](@/w/dziedzic.md) entrance.", source = "M3n747" }
6002 = { path = "wszyscy-lubia-sedziego-michala.webp", caption = "[Sędzia Michał](@/w/sedzia-michal.md) gets some appreciation from Syriusz Dziedzic, Max Speed and the crowd.", source = "M3n747" }
6003 = { path = "szacunek-to-podstawa.webp", caption = "[Syriusz Dziedzic](@/w/dziedzic.md) and [Max Speed](@/w/max-speed.md) shake hands, much to [Sędzia Michał's](@/w/sedzia-michal.md) approval.", source = "M3n747" }
6004 = { path = "jeszcze-niech-go-ktos-karmi-winogronami.webp", caption = "A fan fans Max Speed to bring him relief from the heat.", source = "M3n747" }
6005 = { path = "chwycil-kozak-tatarzyna.webp", caption = "Max Speed intercepts Syriusz Dziedzic's kick.", source = "M3n747" }
6006 = { path = "ten-pan-wygral.webp", caption = "Max Speed wins.", source = "M3n747" }
6007 = { path = "o-tam-cos-jest.webp", caption = "[Max Speed](@/w/max-speed.md) celebrates his victory.", source = "M3n747" }








7001 = { path = ".webp", caption = ".", source = "M3n747" }
8001 = { path = ".webp", caption = ".", source = "M3n747" }
