# On every push this script is executed
on: push
name: Lint and verify metadata
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { issues: write, pull-requests: write }
    steps:
      - uses: actions/checkout@v4
      - name: Install mise and dependencies
        uses: jdx/mise-action@v4
        with:
          tool_versions: |
            zola 0.22.1
            node 24
            python 3.14
            uv 0.10
      - name: Install nodejs modules
        run: npm install
      - name: Build metadata
        run: |
          uv run make all plot
      - name: Run lint and create comment
        run: |
          uv run bin/lint
      - name: Build site
        run: |
          zola build
